package io.com.user.service.UserService;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.stereotype.Service;

import io.com.user.service.UserService.entities.Rating;
import io.com.user.service.UserService.externalService.RatingService;

@SpringBootTest
class UserServiceApplicationTests {

	@Test
	void contextLoads() {
	}
	// just to test feign client for creating rating
	@Autowired
	private RatingService ratingService;
	@Test
	void createRating(){
		Rating rating= Rating.builder().rating(4).userId("").hotelId("").feedback("This is generated by feign client").build();
		Rating savedRating=ratingService.createRating(rating);
		System.out.println("new rating created");
	}
}
