server:
  port: 8081

spring:
  application:
    name: USER-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: Sakshi@90
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  

  config:
    import: configserver:http://localhost:8085
  profiles:
    active: prod

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        inlcude: health

  endpoint:
    health:
      show-details: always


resilience4j:
  circuitbreakers:
    instances:
      ratingHotelBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 2
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

  retry:
    instance:
      ratingHotelService:
          max-attempts: 3
          wait-duration: 5s


  ratelimiter:
    instance:
      UserRateLimiter:
        limit-refresh-period: 4s
        limit-for-period: 2
        timeout-duration: 0s
